# Generated by Django 5.2.8 on 2025-11-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_autor_options_livro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='ISBN',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
